import type { Metadata } from 'next'
import '../globals.scss'
import './default.scss'

export const metadata: Metadata = {
  title: 'OZ Smart Living',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  )
}
