import type { Metadata } from 'next'
import '../globals.scss'
import './common-style.scss'
import Header from './components/Header'
import { Inter } from 'next/font/google'
import FooterComponent from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'OZ Smart Living',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={`${inter.className} overflow-x-hidden`}>
        <Header></Header>
        <div className="bg-zinc-200	w-full min-h-screen flex-col items-center justify-between relative">
          {children}
        </div>
        <FooterComponent />
      </body>
    </html >
  )
}
